# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 472)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.btnLightTheme = QtWidgets.QRadioButton(parent=self.widget)
        self.btnLightTheme.setChecked(True)
        self.btnLightTheme.setObjectName("btnLightTheme")
        self.btnGroupTheme = QtWidgets.QButtonGroup(Form)
        self.btnGroupTheme.setObjectName("btnGroupTheme")
        self.btnGroupTheme.addButton(self.btnLightTheme)
        self.verticalLayout.addWidget(self.btnLightTheme)
        self.btnDarkTheme = QtWidgets.QRadioButton(parent=self.widget)
        self.btnDarkTheme.setObjectName("btnDarkTheme")
        self.btnGroupTheme.addButton(self.btnDarkTheme)
        self.verticalLayout.addWidget(self.btnDarkTheme)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.image = QtWidgets.QLabel(parent=Form)
        self.image.setMinimumSize(QtCore.QSize(600, 450))
        self.image.setMaximumSize(QtCore.QSize(600, 450))
        self.image.setStyleSheet("background: rgb(195, 195, 195)")
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Map"))
        self.label_2.setText(_translate("Form", "Тема"))
        self.btnLightTheme.setText(_translate("Form", "Светлая"))
        self.btnDarkTheme.setText(_translate("Form", "Темная"))
